// <auto-generated />
using AplicatieASP.Components.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicatieASP.Migrations
{
    [DbContext(typeof(BookShelfContext))]
    partial class BookShelfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("webasp")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AplicatieASP.Components.DataBase.Models.FisaDeLucru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FiseDeLucru", "webasp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2021-01-01",
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2021-01-02",
                            Number = "2"
                        });
                });

            modelBuilder.Entity("AplicatieASP.Components.DataBase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", "webasp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane",
                            Password = "5678"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
