// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppAsp.Components.DataBase;

#nullable disable

namespace WebAppAsp.Migrations
{
    [DbContext(typeof(BookShelfContext))]
    [Migration("20240923125255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("webasp")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebAppAsp.Components.DataBase.Models.FisaDeLucru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FiseDeLucru", "webasp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2021-02-01",
                            GPS = "124.456.789",
                            Number = "1"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2021-02-02",
                            GPS = "987.653.321",
                            Number = "2"
                        },
                        new
                        {
                            Id = 3,
                            Date = "2021-03-03",
                            GPS = "987.624.321",
                            Number = "3"
                        });
                });

            modelBuilder.Entity("WebAppAsp.Components.DataBase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", "webasp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John",
                            Password = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane",
                            Password = "5678"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            Password = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
